# -*- coding: utf-8 -*-
"""
/***************************************************************************
 finding_laylines
                                 A QGIS plugin
 This Plugin finds the surface water flow path on a field.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-19
        copyright            : (C) 2021 by FALASY Anamelechi
        email                : fvw.services@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load finding_laylines class from file finding_laylines.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .finding_laylines import finding_laylines
    return finding_laylines(iface)
